# Generated by Django 3.2.5 on 2023-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('duration', models.CharField(max_length=22)),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('prerequisite', models.CharField(max_length=100)),
                ('Fee', models.IntegerField(null=True)),
            ],
        ),
    ]
