# Generated by Django 3.2.5 on 2023-03-06 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('duration', models.CharField(max_length=22)),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('prerequisite', models.CharField(max_length=100)),
                ('Fee', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=100)),
                ('father_contact', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('show', models.BooleanField(default=False)),
                ('selected_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
