# Generated by Django 3.2.5 on 2023-02-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('father_contact', models.CharField(max_length=100)),
                ('selected_course', models.CharField(max_length=100)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
