# Generated by Django 3.2.5 on 2023-03-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='show',
        ),
    ]
